### ISSUE TITLE
local variable 'conf' referenced before assignment

### ISSUE THREAD

**Issue by odradekk** [0x4D31/honeyku#1]
I deploy this honeypot in a docker  https://hub.docker.com/r/dickeyxxx/heroku-cli/
`docker pull dickeyxxx/heroku-cli:latest`

and this honeypot crashed as listed
![qq 20180815110940](https://user-images.githubusercontent.com/23138452/44129591-b6b9fe44-a07b-11e8-8668-1522e060a1b4.png)

**Comment by odradekk** [comment]
The problem has been sloved, only use local config will fix the problem. beacause the s3 is not supported
now.

**Comment by 0x4D31** [comment]
@A5sho1e Right. Will add the S3 module soon. Cheers,
